import { uuid } from "./uuid";
import {
  React,
  Javascript,
  HTMLCSS,
  Tailwind,
  FlexAndGrid,
  FreeLance,
  Git,
  VsCode,
} from "../assets/images/index";

export const data = [
  {
    text: "دوره حرفه ای متخصص ریکت و ریداکس",
    time: 40,
    price: 2_298_000,
    id: uuid(),
    category: "js",
    image: React,
  },
  {
    text: "دوره جامع و پیشرفته جاواسکریپت",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "js",
    image: Javascript,
  },
  {
    text: "دوره جامع و پیشرفته تیلویند",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "css",
    image: Tailwind,
  },
  {
    text: "دوره جامع و پیشرفته طراحی وب",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "css",
    image: HTMLCSS,
  },
  {
    text: "دوره جامع و پیشرفته گیت و گیت هاب",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "git",
    image: Git,
  },
  {
    text: "دوره جامع و پیشرفته فلکس و گرید",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "css",
    image: FlexAndGrid,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
  {
    text: "دوره جامع و پیشرفته Vs Code ",
    time: 27,
    price: 1_539_000,
    id: uuid(),
    category: "other",
    image: VsCode,
  },
];

export const filteringLogic = (products, category) => {
  const filteredProducts = products.filter((p) => p.category === category);
  return filteredProducts;
};
